version: 0.0
os: linux
files:
   - source: /
     destination: /var/games
hooks:
   BeforeInstall:
    - location: scripts/installnpm.sh
      runas: root
   AfterInstall:
    - location: scripts/installnodemodules.sh
      runas: root